// GENERATED by scripts/generate-databricks-model-names.py
// Source:  https://models.dev/api.json -- providers.databricks.models
// Refresh: python3 scripts/generate-databricks-model-names.py
//
// Do not hand-edit -- rerun the script to update.

/**
 * Curated display names for known Databricks AI Gateway endpoints.
 *
 * Keys are endpoint IDs returned verbatim by the discovery APIs.
 * Values are human-readable display names sourced from models.dev.
 *
 * Unknown endpoint IDs are resolved by resolveModelLabel() as raw IDs.
 * Use a Map to avoid Object.prototype key collisions.
 */
export const DATABRICKS_MODEL_NAMES: Map<string, string> = new Map([
  ["databricks-claude-haiku-4-5", "Claude Haiku 4.5 (latest)"],
  ["databricks-claude-opus-4-1", "Claude Opus 4.1 (latest)"],
  ["databricks-claude-opus-4-5", "Claude Opus 4.5 (latest)"],
  ["databricks-claude-opus-4-6", "Claude Opus 4.6"],
  ["databricks-claude-opus-4-7", "Claude Opus 4.7"],
  ["databricks-claude-sonnet-4", "Claude Sonnet 4.5"],
  ["databricks-claude-sonnet-4-5", "Claude Sonnet 4.5 (latest)"],
  ["databricks-claude-sonnet-4-6", "Claude Sonnet 4.6"],
  ["databricks-gemini-2-5-flash", "Gemini 2.5 Flash"],
  ["databricks-gemini-2-5-pro", "Gemini 2.5 Pro"],
  ["databricks-gemini-3-1-flash-lite", "Gemini 3.1 Flash Lite Preview"],
  ["databricks-gemini-3-1-pro", "Gemini 3.1 Pro Preview Custom Tools"],
  ["databricks-gemini-3-flash", "Gemini 3 Flash Preview"],
  ["databricks-gemini-3-pro", "Gemini 3 Pro Preview"],
  ["databricks-glm-5-2", "GLM-5.2"],
  ["databricks-gpt-5", "GPT-5"],
  ["databricks-gpt-5-1", "GPT-5.1"],
  ["databricks-gpt-5-2", "GPT-5.2"],
  ["databricks-gpt-5-4", "GPT-5.4"],
  ["databricks-gpt-5-4-mini", "GPT-5.4 mini"],
  ["databricks-gpt-5-4-nano", "GPT-5.4 nano"],
  ["databricks-gpt-5-5", "GPT-5.5"],
  ["databricks-gpt-5-6-luna", "GPT-5.6 Luna"],
  ["databricks-gpt-5-6-sol", "GPT-5.6 Sol"],
  ["databricks-gpt-5-6-terra", "GPT-5.6 Terra"],
  ["databricks-gpt-5-mini", "GPT-5 Mini"],
  ["databricks-gpt-5-nano", "GPT-5 Nano"],
  ["databricks-gpt-oss-120b", "GPT OSS 120B"],
  ["databricks-gpt-oss-20b", "GPT OSS 20B"],
  ["databricks-kimi-k2-7-code", "Kimi K2.7 Code"],
]);
